#!/usr/bin/env python3
import sys
import os

from analyzer import Analyzer
from termcolor import colored
import helpers

# TODO
def main():
    #accepts one and only one command-line argument, the screen name for a user on Twitter
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")

    #queries Twitter’s API for a user’s most recent 50 tweets
    Tweets = helpers.get_user_timeline(sys.argv[1], 50) #Learn: 1. must import helpers 2. must put helpers.xxxxx.xx

    if Tweets == None:
        sys.exit("screen name does not exist/is protected")


    #analyzes the sentiment of each of those tweets
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    analyzer = Analyzer(positives, negatives)



    #outputs each tweet’s score and text, colored in green if positive, red if negative, and yellow otherwise
    for tweet in Tweets: #Learn: is it because Tweets is not a text but a file???So I need to use for-loop?
        score = analyzer.analyze(tweet) #Tweets Here
        if score > 0.0:
            print(colored("{} {}".format(score,tweet), "green"))
        elif score < 0.0:
            print(colored("{} {}".format(score,tweet), "red"))
        else:
            print(colored("{} {}".format(score,tweet), "yellow"))


if __name__ == "__main__":
    main()